### ISSUE TITLE
Is FontAwesome glyphs being pixelized and cut-off on scroll normal?

### ISSUE THREAD

**Issue by SuperPrower** [blueyed/PKGBUILD-rxvt-unicode-wide#3]
Hello! I have installed your patched version trough AUR, but I experience some weird stuff with glyph fonts.

I add fontawesome to my .Xresources like this:

```
URxvt*font:		xft:xos4 Terminus:pixelsize=18, \
			xft:xos4 Terminess Powerline:pixelsize=18, \
			-*-fontawesome-*-*-*-*-*-*-*-*-*-*-*-*

URxvt*boldFont:		xtf:xos4 Terminus:pixelsize=18:weight=bold, \
			xft:xos4 Terminess Powerline:pixelsize=18, \
			-*-fontawesome-*-*-*-*-*-*-*-*-*-*-*-*
```
I couldn't get regular way to work:
```
$ urxvt -fn "xft:FontAwesome"
urxvt: unable to calculate font width for 'FontAwesome:minspace=True', ignoring.
urxvt: unable to load base fontset, please specify a valid one using -fn, aborting.
```

So in the end, I get something like this (screenshot from vim):

![fa](https://user-images.githubusercontent.com/10908110/36665655-36067a8c-1af9-11e8-82d1-35e02a91e9cd.png)

As you can see, glyphs look pixelized, some glyphs are cut in half, and scrolling randomly fixes this. I _suspect_ this has something to do with way I included FontAwesome, but as I said, I couldn't make other way work.

I would be glad if you suggested a better way to use such fonts. Thanks!

**Comment by blueyed** [comment]
Thanks for the report.

I've finally included a patch I've posted in 2016 already to make urxvt recognize FontAwesome after all.

Another option would be to use a patch font, where FontAwesome is included, e.g. "UbuntuMonoDerivativePowerline Nerd Font".

**Comment by SuperPrower** [comment]
Wow, thanks!
But what would be the correct way to include FontAwesome in xresources?
This still doesn't seem to work:

```
$ urxvt -fn "xft:Font Awesome"
urxvt: unable to calculate font width for 'Font Awesome:minspace=True', ignoring.
urxvt: unable to load base fontset, please specify a valid one using -fn, aborting.
```

**Comment by blueyed** [comment]
You can use `fc-match` to find what to use.  For me on Arch with otf-font-awesome it is 'Font Awesome 5 Free'.
However, that will make this build segfault (`/usr/bin/urxvt -fn 'xft:Font Awesome 5 Free'`) - can you confirm that?

But even when it is not crashing (with the local patches I am using) it still loads other fonts additionally, and does not display e.g. https://fontawesome.com/icons/github-square?style=brands () for me.

**Comment by SuperPrower** [comment]
I am using `ttf-font-awesome-4` from AUR, but I tried and installed Font Awesome 5, and it is still producing this error:

```
[superprower@latitude ~]$ pacman -Qs urxvt
local/rxvt-unicode-cvs-patched-wideglyphs 20170412-6
    Unicode enabled rxvt-clone terminal emulator (urxvt) with fixed font spacing and wide glyphs patch (cvs version)
local/rxvt-unicode-terminfo 9.22-5
    Terminfo files for urxvt
[superprower@latitude ~]$ /usr/bin/urxvt -fn 'xft:Font Awesome 5 Free'
urxvt: unable to calculate font width for 'Font Awesome 5 Free:minspace=True', ignoring.
urxvt: unable to load base fontset, please specify a valid one using -fn, aborting.
[superprower@latitude ~]$ 
```

Are we even talking about same version? Should I use some other version, not one from AUR linked in this repository description?

**Comment by blueyed** [comment]
Yes, the version is correct.
What does `fc-match "Font Awesome 5 Free"` and `fc-match Awesome` give you?

**Comment by blueyed** [comment]
Anyway, at least when only using this font I get a segfault and it is related to this patch doing something wrong.
I have a heavily changed local patch, but need some time to clean and push it.

You might be better off for now to use a patched nerd font probably.
(still interested in the fc-match of course and if it segfaults for you also)

**Comment by SuperPrower** [comment]
```
[superprower@latitude ~]$ fc-match "Font Awesome 5 Free"
fa-regular-400.ttf: "Font Awesome 5 Free" "Regular"
[superprower@latitude ~]$ fc-match Awesome
DejaVuSans.ttf: "DejaVu Sans" "Book"
[superprower@latitude ~]$ 
```

I'm kinda ok with this dash-star-dash-star version - it's not perfect, but at least I know what icon is what in my config.
