### ISSUE TITLE
Problems with some glyphs

### ISSUE THREAD

**Issue by slackhead** [blueyed/PKGBUILD-rxvt-unicode-wide#4]
Hi

I have a problem with some glyphs in email from Ebay. The characters show properly, but the following line(s) are eaten.

Screenshot here to show you what I mean:

http://www.r0t.uk/sshots/shot-5880465154.png

And rxvt-unicode identifies the delivery van as 1f69a in Symbola font and the tick as 2705 also in Symbola:

http://www.r0t.uk/sshots/shot-6168817166.png

I'm using your patches with a SlackBuild rather than the PKGBUILD:

http://dawoodfall.net/slackbuilds/14.2/rxvt-unicode/

But I've checked that the wide-glyph is up-to-date with yours.

Oh, I'm also using doc/wcwidth.patch that is included in the source. I've tried with and without it, but don't see any difference with this problem.

**Comment by blueyed** [comment]
Do you mean that the following lines lose their indentation?
Looks like a bug in mutt maybe..  please try copy'n'pasting it from the term/mutt to a text file and then see how it behaves in vim/emacs and with `cat`.

**Comment by slackhead** [comment]
Ah yes. The indentation is fine in vim (although the end of van is cut short).

cat displays the van correctly. I'll see if I can find a mutt patch for this.

**Comment by slackhead** [comment]
Well I haven't yet found a solution, but I can close this because I've found that it seems to be a problem with screen + mutt.

mutt without screen = OK
vim in screen = OK
less in screen = OK
cat in screen = OK

**Comment by blueyed** [comment]
Is tmux + mutt also affected?

**Comment by slackhead** [comment]
I've not tried tmux with mutt. I don't have it installed. I did try it once but it seems it doesn't support a separate window list (caption) and status line like screen does.

I've narrowed it down a bit though. screen 4.4.0 (default on slackware) is OK.
Screen 4.6.2 or later is broken.

So for now I'm back on 4.4.0.

**Comment by blueyed** [comment]
Good findings.  This could be used to bisect it if you want to investigate further - but maybe the local changes for the patch help already / fix it (so you might want to wait instead).

As for tmux vs screen, I've found the former to be better in general and switched a long time ago already.  Not sure about the features you are missing though.
